# Historical Pandemic Epidemic

### collecting Data :

In [34]:
import pandas as pd ;
df = pd.read_csv(r"C:\Users\ELBOSTAN\ML_Project\Data\Historical_Pandemic_Epidemic_Dataset.csv")
df

,Event_Name,Pathogen_Name,Pathogen_Type,Start_Year,End_Year,Duration_Years,Origin_Region,Geographic_Spread,Continents_Affected,Estimated_Cases,...,Case_Fatality_Rate_Pct,Primary_Transmission,Containment_Method,Economic_Impact_Billion_USD,Medical_Breakthrough,Era,WHO_Classification,Mortality_Scale,Spread_Score,Century
0,Black Death,Yersinia pestis,Bacteria,1347,1353.0,6.0,Central Asia,Global,6,2.000000e+08,...,37.500,Vector/Contact,Natural Decline,NaN,True,Medieval,Pandemic,Catastrophic,22.5000,14th Century
1,Plague of Justinian,Yersinia pestis,Bacteria,541,549.0,8.0,Egypt,Continental,4,5.000000e+07,...,50.000,Vector,Natural Decline,NaN,False,Ancient,Pandemic,Catastrophic,20.0000,6th Century
2,Antonine Plague,Smallpox/Measles,Virus,165,180.0,15.0,Near East,Continental,3,1.000000e+07,...,50.000,Contact,Natural Decline,200.0,False,Ancient,Pandemic,High,15.0000,2th Century
3,Second Pandemic Plague,Yersinia pestis,Bacteria,1361,1363.0,2.0,Europe,Continental,2,3.000000e+07,...,40.000,Vector,Natural Decline,100.0,False,Medieval,Pandemic,Catastrophic,8.0000,14th Century
4,Sweating Sickness,Unknown,Unknown,1485,1551.0,66.0,England,Regional,1,NaN,...,16.700,Unknown,Natural Decline,10.0,False,Medieval,Epidemic,Low,1.6700,15th Century
5,Smallpox in Americas,Variola major,Virus,1519,1600.0,81.0,Europe,Continental,2,6.000000e+07,...,93.300,Contact,NaN,100.0,False,Early_Modern,NaN,Catastrophic,10.0000,16th Century
6,Sixth Cholera Pandemic,Vibrio cholerae,Bacteria,1899,1923.0,24.0,India,Global,6,5.000000e+06,...,36.000,Waterborne,Sanitation,150.0,False,Industrial,Pandemic,High,21.6000,19th Century
7,Great Plague of London,Yersinia pestis,Bacteria,1665,1666.0,1.0,England,Regional,1,9.730600e+04,...,70.500,Vector,Quarantine,50.0,False,Early_Modern,NaN,Moderate,5.0000,17th Century
8,Great Plague of Marseille,Yersinia pestis,Bacteria,1720,1722.0,2.0,France,Regional,1,1.200000e+05,...,41.700,Vector,Quarantine,30.0,False,Early_Modern,Epidemic,Low,4.1700,18th Century
9,First Cholera Pandemic,Vibrio cholerae,Bacteria,1817,1824.0,7.0,India,Continental,3,1.500000e+06,...,33.300,Waterborne,Quarantine,20.0,False,Early_Modern,Pandemic,Moderate,9.9900,19th Century
10,Second Cholera Pandemic,Vibrio cholerae,Bacteria,1829,1837.0,8.0,India,Global,5,2.500000e+06,...,36.000,Waterborne,Quarantine,50.0,False,Early_Modern,Pandemic,Moderate,18.0000,19th Century
11,Third Cholera Pandemic,Vibrio cholerae,Bacteria,1839,1856.0,17.0,India,Global,6,3.000000e+06,...,33.300,Waterborne,Sanitation,80.0,False,Early_Modern,Pandemic,Moderate,19.9800,19th Century
12,Fourth Cholera Pandemic,Vibrio cholerae,Bacteria,1863,1875.0,12.0,India,Global,6,3.500000e+06,...,34.300,Waterborne,Sanitation,90.0,False,Industrial,Pandemic,High,20.5800,19th Century
13,Fifth Cholera Pandemic,Vibrio cholerae,Bacteria,1881,1896.0,15.0,India,Global,6,4.000000e+06,...,35.000,Waterborne,Sanitation,100.0,False,Industrial,Pandemic,High,21.0000,19th Century
14,Sixth Cholera Pandemic,Vibrio cholerae,Bacteria,1899,1923.0,24.0,India,Global,6,5.000000e+06,...,36.000,Waterborne,Sanitation,150.0,False,Industrial,Pandemic,High,21.6000,19th Century
15,Russian Flu,H2N2 Influenza,Virus,1889,1890.0,1.0,Russia,Global,6,1.000000e+09,...,0.100,Airborne,Natural Decline,200.0,False,Industrial,Pandemic,Moderate,0.0600,19th Century
16,Yellow Fever Epidemic,Yellow Fever Virus,Virus,1793,1798.0,5.0,USA,Regional,1,1.000000e+04,...,50.000,Vector,Quarantine,5.0,False,Industrial,Epidemic,Low,5.0000,18th Century
17,Typhus Epidemic WWI,Rickettsia prowazekii,Bacteria,1914,1918.0,4.0,Eastern Europe,Continental,3,3.000000e+07,...,10.000,Vector,Delousing,50.0,False,Industrial,Epidemic,High,3.0000,20th Century
18,Spanish Flu,H1N1 Influenza,Virus,1918,1920.0,2.0,USA,Global,6,5.000000e+08,...,10.000,Airborne,Quarantine,2500.0,True,Industrial,Pandemic,Catastrophic,6.0000,20th Century
19,Encephalitis Lethargica,Unknown,Unknown,1915,1926.0,11.0,Europe,Continental,3,NaN,...,50.000,Unknown,Supportive Care,30.0,False,Industrial,Epidemic,Moderate,15.0000,20th Century
20,Asian Flu,H2N2 Influenza,Virus,1957,1958.0,1.0,China,Global,6,2.000000e+09,...,0.055,Airborne,Vaccine,5000.0,True,Modern,Pandemic,High,0.0330,20th Century
21,Hong Kong Flu,H3N2 Influenza,Virus,1968,1970.0,2.0,China,Global,6,1.500000e+09,...,0.067,Airborne,Vaccine,4000.0,True,Modern,Pandemic,Moderate,0.0402,20th Century
22,Zika Virus,Zika Virus,Virus,2015,NaN,NaN,Brazil,Continental,3,5.000000e+05,...,0.400,Vector/Sexual,Supportive Care,10.0,True,Contemporary,Epidemic,Low,0.1200,21st Century
23,Smallpox Eradication,Variola major,Virus,1967,1980.0,13.0,Global,Global,7,1.500000e+07,...,13.300,Contact,Vaccine,100.0,True,Modern,Pandemic,High,9.3100,20th Century
24,Legionnaires Disease,Legionella,Bacteria,1976,1977.0,1.0,USA,Local,1,2.210000e+02,...,15.400,Airborne,Antibiotics,1.0,True,Modern,Outbreak,Minimal,1.5400,20th Century
25,HIV/AIDS,HIV,Virus,1981,NaN,NaN,DRC,Global,7,8.400000e+07,...,47.600,Sexual/Blood,Antiretroviral,2400.0,True,Modern,Pandemic,Catastrophic,33.3200,20th Century
26,Seventh Cholera Pandemic,Vibrio cholerae El Tor,Bacteria,1961,2023.0,62.0,Indonesia,Global,6,2.800000e+06,...,3.400,Waterborne,ORS/Vaccine,500.0,True,Modern,Pandemic,Moderate,2.0400,20th Century
27,Dengue Fever,Dengue Virus,Virus,1970,NaN,NaN,Tropical Regions,Global,5,5.000000e+08,...,0.005,Vector,Supportive Care,900.0,True,Modern,Endemic,Low,0.0025,20th Century
28,Polio (Pre-Eradication),Poliovirus,Virus,1916,2023.0,107.0,USA,Global,7,6.500000e+05,...,1.500,Fecal-Oral,Vaccine,200.0,True,Modern,Pandemic,Low,1.0500,20th Century
29,Lassa Fever,Lassa Virus,Virus,1969,2023.0,54.0,Nigeria,Regional,1,3.000000e+05,...,1.700,Contact,Supportive Care,5.0,True,Modern,Epidemic,Low,0.1700,20th Century
30,West Nile Virus,West Nile Virus,Virus,1999,2023.0,24.0,USA/Africa,Continental,4,8.000000e+06,...,0.025,Vector,Supportive Care,50.0,True,Modern,Epidemic,Low,0.0100,20th Century
31,SARS,SARS-CoV-1,Virus,2002,2004.0,2.0,China,Continental,5,8.098000e+03,...,9.560,Airborne/Droplet,Quarantine,30.0,True,Contemporary,Epidemic,Minimal,4.7800,21st Century
32,H5N1 Bird Flu,H5N1 Influenza,Virus,1997,2023.0,26.0,China,Regional,3,8.680000e+02,...,52.600,Contact,Antiviral,10.0,True,Contemporary,Epidemic,Minimal,15.0000,20th Century
33,2009 Swine Flu,H1N1 Influenza,Virus,2009,2010.0,1.0,Mexico,Global,6,7.000000e+08,...,0.040,Airborne,Vaccine,75.0,True,Contemporary,Pandemic,Moderate,0.0240,21st Century
34,MERS,MERS-CoV,Virus,2012,2023.0,11.0,Saudi Arabia,Regional,2,2.600000e+03,...,35.960,Droplet/Camel,Isolation,20.0,True,Contemporary,Epidemic,Minimal,7.1920,21st Century
35,West Africa Ebola,Ebola Virus,Virus,2014,2016.0,2.0,Guinea,Regional,1,2.861600e+04,...,39.500,Contact,Supportive Care,53.0,True,Contemporary,Epidemic,Low,3.9500,21st Century
36,Zika Virus,Zika Virus,Virus,2015,2016.0,1.0,Brazil,Continental,3,5.000000e+05,...,0.400,Vector/Sexual,Supportive Care,10.0,True,Contemporary,Epidemic,Low,0.1200,21st Century
37,COVID-19,SARS-CoV-2,Virus,2019,2023.0,4.0,China,Global,7,7.000000e+08,...,1.000,Airborne/Droplet,Vaccine/Lockdown,13800.0,True,Contemporary,Pandemic,High,0.7000,21st Century
38,Monkeypox 2022,Monkeypox Virus,Virus,2022,2023.0,1.0,Multiple,Global,6,9.000000e+04,...,0.110,Contact,Vaccine,3.0,True,Contemporary,Epidemic,Minimal,0.0660,21st Century
39,Cholera Haiti,Vibrio cholerae,Bacteria,2010,2019.0,9.0,Haiti,Regional,1,8.200000e+05,...,1.160,Waterborne,ORS,2.0,False,Contemporary,Epidemic,Low,0.1160,21st Century
40,Yellow Fever Angola,Yellow Fever Virus,Virus,2015,2016.0,1.0,Angola,Regional,1,7.334000e+03,...,4.840,Vector,Vaccine,1.0,True,Contemporary,Outbreak,Minimal,0.4840,21st Century
41,Plague Madagascar,Yersinia pestis,Bacteria,2017,2017.0,1.0,Madagascar,Local,1,2.348000e+03,...,8.600,Airborne/Vector,Antibiotics,1.0,True,Contemporary,Outbreak,Minimal,0.8600,21st Century
42,Nipah Virus Kerala,Nipah Virus,Virus,2018,2023.0,5.0,India,Local,1,2.300000e+01,...,91.300,Contact/Bats,Isolation,1.0,True,Contemporary,Outbreak,Minimal,5.0000,21st Century
43,Marburg Germany,Marburg Virus,Virus,1967,1967.0,1.0,Germany,Local,1,3.100000e+01,...,NaN,Contact,Isolation,1.0,True,Modern,Outbreak,Minimal,2.2600,20th Century
44,Typhoid Fever Pakistan,Salmonella Typhi,Bacteria,2016,2023.0,7.0,Pakistan,Regional,1,1.000000e+04,...,1.000,Waterborne/Food,Antibiotics,3.0,True,Contemporary,Epidemic,Minimal,0.1000,21st Century
45,Measles DRC,Measles Virus,Virus,2019,2020.0,1.0,DRC,Regional,1,3.100000e+05,...,1.940,Airborne,Vaccine,2.0,False,Contemporary,Epidemic,Low,0.1940,21st Century
46,Pertussis USA,Bordetella pertussis,Bacteria,2012,2013.0,1.0,USA,Regional,1,4.827700e+04,...,0.040,Airborne,Vaccine,1.0,True,Contemporary,Epidemic,Minimal,0.0040,21st Century
47,Meningitis Belt Africa,Neisseria meningitidis,Bacteria,2009,2010.0,1.0,Africa,Regional,1,8.819900e+04,...,6.070,Droplet,Vaccine,3.0,True,Contemporary,Epidemic,Low,0.6070,21st Century
48,Anthrax Siberia,Bacillus anthracis,Bacteria,2016,2016.0,1.0,Russia,Local,1,2.300000e+03,...,0.040,Contact,Antibiotics,1.0,False,Contemporary,Outbreak,Minimal,0.0040,21st Century
49,Rocky Mountain Spotted Fever,Rickettsia rickettsii,Bacteria,1980,2023.0,43.0,USA,Regional,1,6.000000e+03,...,1.000,Vector,Antibiotics,2.0,True,Modern,Endemic,Minimal,0.1000,20th Century
50,Hantavirus,Hantavirus,Virus,1993,2023.0,30.0,USA,Regional,2,8.330000e+02,...,37.300,Contact,Supportive Care,2.0,True,Modern,Endemic,Minimal,7.4600,20th Century
51,Q Fever Netherlands,Coxiella burnetii,Bacteria,2007,2010.0,3.0,Netherlands,Regional,1,4.000000e+03,...,1.850,Airborne,Antibiotics,1.0,True,Contemporary,Epidemic,Minimal,0.1850,21st Century
52,Sweating Sickness,Unknown,Unknown,1485,1551.0,66.0,England,Regional,1,NaN,...,16.700,Unknown,Natural Decline,10.0,False,Medieval,Epidemic,Low,1.6700,15th Century

In [35]:
df.info();

<class 'pandas.DataFrame'>
RangeIndex: 53 entries, 0 to 52
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Event_Name                   53 non-null     str
 1   Pathogen_Name                53 non-null     str
 2   Pathogen_Type                53 non-null     str
 3   Start_Year                   53 non-null     int64
 4   End_Year                     50 non-null     float64
 5   Duration_Years               50 non-null     float64
 6   Origin_Region                53 non-null     str
 7   Geographic_Spread            53 non-null     str
 8   Continents_Affected          53 non-null     int64
 9   Estimated_Cases              50 non-null     float64
 10  Estimated_Deaths             53 non-null     int64
 11  Case_Fatality_Rate_Pct       52 non-null     float64
 12  Primary_Transmission         53 non-null     str
 13  Containment_Method           52 non-null     str
 14  Economic_Impact_Billion_USD  51 non-null     float64
 15  Medical_Breakthrough         53 non-null     bool
 16  Era                          53 non-null     str
 17  WHO_Classification           51 non-null     str
 18  Mortality_Scale              53 non-null     str
 19  Spread_Score                 53 non-null     float64
 20  Century                      53 non-null     str
dtypes: bool(1), float64(6), int64(3), str(11)
memory usage: 8.5 KB

### Cleaning Data :

#### Dublication :

In [36]:
df.duplicated().sum()
df = df.drop_duplicates()
df

,Event_Name,Pathogen_Name,Pathogen_Type,Start_Year,End_Year,Duration_Years,Origin_Region,Geographic_Spread,Continents_Affected,Estimated_Cases,...,Case_Fatality_Rate_Pct,Primary_Transmission,Containment_Method,Economic_Impact_Billion_USD,Medical_Breakthrough,Era,WHO_Classification,Mortality_Scale,Spread_Score,Century
0,Black Death,Yersinia pestis,Bacteria,1347,1353.0,6.0,Central Asia,Global,6,2.000000e+08,...,37.500,Vector/Contact,Natural Decline,NaN,True,Medieval,Pandemic,Catastrophic,22.5000,14th Century
1,Plague of Justinian,Yersinia pestis,Bacteria,541,549.0,8.0,Egypt,Continental,4,5.000000e+07,...,50.000,Vector,Natural Decline,NaN,False,Ancient,Pandemic,Catastrophic,20.0000,6th Century
2,Antonine Plague,Smallpox/Measles,Virus,165,180.0,15.0,Near East,Continental,3,1.000000e+07,...,50.000,Contact,Natural Decline,200.0,False,Ancient,Pandemic,High,15.0000,2th Century
3,Second Pandemic Plague,Yersinia pestis,Bacteria,1361,1363.0,2.0,Europe,Continental,2,3.000000e+07,...,40.000,Vector,Natural Decline,100.0,False,Medieval,Pandemic,Catastrophic,8.0000,14th Century
4,Sweating Sickness,Unknown,Unknown,1485,1551.0,66.0,England,Regional,1,NaN,...,16.700,Unknown,Natural Decline,10.0,False,Medieval,Epidemic,Low,1.6700,15th Century
5,Smallpox in Americas,Variola major,Virus,1519,1600.0,81.0,Europe,Continental,2,6.000000e+07,...,93.300,Contact,NaN,100.0,False,Early_Modern,NaN,Catastrophic,10.0000,16th Century
6,Sixth Cholera Pandemic,Vibrio cholerae,Bacteria,1899,1923.0,24.0,India,Global,6,5.000000e+06,...,36.000,Waterborne,Sanitation,150.0,False,Industrial,Pandemic,High,21.6000,19th Century
7,Great Plague of London,Yersinia pestis,Bacteria,1665,1666.0,1.0,England,Regional,1,9.730600e+04,...,70.500,Vector,Quarantine,50.0,False,Early_Modern,NaN,Moderate,5.0000,17th Century
8,Great Plague of Marseille,Yersinia pestis,Bacteria,1720,1722.0,2.0,France,Regional,1,1.200000e+05,...,41.700,Vector,Quarantine,30.0,False,Early_Modern,Epidemic,Low,4.1700,18th Century
9,First Cholera Pandemic,Vibrio cholerae,Bacteria,1817,1824.0,7.0,India,Continental,3,1.500000e+06,...,33.300,Waterborne,Quarantine,20.0,False,Early_Modern,Pandemic,Moderate,9.9900,19th Century
10,Second Cholera Pandemic,Vibrio cholerae,Bacteria,1829,1837.0,8.0,India,Global,5,2.500000e+06,...,36.000,Waterborne,Quarantine,50.0,False,Early_Modern,Pandemic,Moderate,18.0000,19th Century
11,Third Cholera Pandemic,Vibrio cholerae,Bacteria,1839,1856.0,17.0,India,Global,6,3.000000e+06,...,33.300,Waterborne,Sanitation,80.0,False,Early_Modern,Pandemic,Moderate,19.9800,19th Century
12,Fourth Cholera Pandemic,Vibrio cholerae,Bacteria,1863,1875.0,12.0,India,Global,6,3.500000e+06,...,34.300,Waterborne,Sanitation,90.0,False,Industrial,Pandemic,High,20.5800,19th Century
13,Fifth Cholera Pandemic,Vibrio cholerae,Bacteria,1881,1896.0,15.0,India,Global,6,4.000000e+06,...,35.000,Waterborne,Sanitation,100.0,False,Industrial,Pandemic,High,21.0000,19th Century
15,Russian Flu,H2N2 Influenza,Virus,1889,1890.0,1.0,Russia,Global,6,1.000000e+09,...,0.100,Airborne,Natural Decline,200.0,False,Industrial,Pandemic,Moderate,0.0600,19th Century
16,Yellow Fever Epidemic,Yellow Fever Virus,Virus,1793,1798.0,5.0,USA,Regional,1,1.000000e+04,...,50.000,Vector,Quarantine,5.0,False,Industrial,Epidemic,Low,5.0000,18th Century
17,Typhus Epidemic WWI,Rickettsia prowazekii,Bacteria,1914,1918.0,4.0,Eastern Europe,Continental,3,3.000000e+07,...,10.000,Vector,Delousing,50.0,False,Industrial,Epidemic,High,3.0000,20th Century
18,Spanish Flu,H1N1 Influenza,Virus,1918,1920.0,2.0,USA,Global,6,5.000000e+08,...,10.000,Airborne,Quarantine,2500.0,True,Industrial,Pandemic,Catastrophic,6.0000,20th Century
19,Encephalitis Lethargica,Unknown,Unknown,1915,1926.0,11.0,Europe,Continental,3,NaN,...,50.000,Unknown,Supportive Care,30.0,False,Industrial,Epidemic,Moderate,15.0000,20th Century
20,Asian Flu,H2N2 Influenza,Virus,1957,1958.0,1.0,China,Global,6,2.000000e+09,...,0.055,Airborne,Vaccine,5000.0,True,Modern,Pandemic,High,0.0330,20th Century
21,Hong Kong Flu,H3N2 Influenza,Virus,1968,1970.0,2.0,China,Global,6,1.500000e+09,...,0.067,Airborne,Vaccine,4000.0,True,Modern,Pandemic,Moderate,0.0402,20th Century
22,Zika Virus,Zika Virus,Virus,2015,NaN,NaN,Brazil,Continental,3,5.000000e+05,...,0.400,Vector/Sexual,Supportive Care,10.0,True,Contemporary,Epidemic,Low,0.1200,21st Century
23,Smallpox Eradication,Variola major,Virus,1967,1980.0,13.0,Global,Global,7,1.500000e+07,...,13.300,Contact,Vaccine,100.0,True,Modern,Pandemic,High,9.3100,20th Century
24,Legionnaires Disease,Legionella,Bacteria,1976,1977.0,1.0,USA,Local,1,2.210000e+02,...,15.400,Airborne,Antibiotics,1.0,True,Modern,Outbreak,Minimal,1.5400,20th Century
25,HIV/AIDS,HIV,Virus,1981,NaN,NaN,DRC,Global,7,8.400000e+07,...,47.600,Sexual/Blood,Antiretroviral,2400.0,True,Modern,Pandemic,Catastrophic,33.3200,20th Century
26,Seventh Cholera Pandemic,Vibrio cholerae El Tor,Bacteria,1961,2023.0,62.0,Indonesia,Global,6,2.800000e+06,...,3.400,Waterborne,ORS/Vaccine,500.0,True,Modern,Pandemic,Moderate,2.0400,20th Century
27,Dengue Fever,Dengue Virus,Virus,1970,NaN,NaN,Tropical Regions,Global,5,5.000000e+08,...,0.005,Vector,Supportive Care,900.0,True,Modern,Endemic,Low,0.0025,20th Century
28,Polio (Pre-Eradication),Poliovirus,Virus,1916,2023.0,107.0,USA,Global,7,6.500000e+05,...,1.500,Fecal-Oral,Vaccine,200.0,True,Modern,Pandemic,Low,1.0500,20th Century
29,Lassa Fever,Lassa Virus,Virus,1969,2023.0,54.0,Nigeria,Regional,1,3.000000e+05,...,1.700,Contact,Supportive Care,5.0,True,Modern,Epidemic,Low,0.1700,20th Century
30,West Nile Virus,West Nile Virus,Virus,1999,2023.0,24.0,USA/Africa,Continental,4,8.000000e+06,...,0.025,Vector,Supportive Care,50.0,True,Modern,Epidemic,Low,0.0100,20th Century
31,SARS,SARS-CoV-1,Virus,2002,2004.0,2.0,China,Continental,5,8.098000e+03,...,9.560,Airborne/Droplet,Quarantine,30.0,True,Contemporary,Epidemic,Minimal,4.7800,21st Century
32,H5N1 Bird Flu,H5N1 Influenza,Virus,1997,2023.0,26.0,China,Regional,3,8.680000e+02,...,52.600,Contact,Antiviral,10.0,True,Contemporary,Epidemic,Minimal,15.0000,20th Century
33,2009 Swine Flu,H1N1 Influenza,Virus,2009,2010.0,1.0,Mexico,Global,6,7.000000e+08,...,0.040,Airborne,Vaccine,75.0,True,Contemporary,Pandemic,Moderate,0.0240,21st Century
34,MERS,MERS-CoV,Virus,2012,2023.0,11.0,Saudi Arabia,Regional,2,2.600000e+03,...,35.960,Droplet/Camel,Isolation,20.0,True,Contemporary,Epidemic,Minimal,7.1920,21st Century
35,West Africa Ebola,Ebola Virus,Virus,2014,2016.0,2.0,Guinea,Regional,1,2.861600e+04,...,39.500,Contact,Supportive Care,53.0,True,Contemporary,Epidemic,Low,3.9500,21st Century
36,Zika Virus,Zika Virus,Virus,2015,2016.0,1.0,Brazil,Continental,3,5.000000e+05,...,0.400,Vector/Sexual,Supportive Care,10.0,True,Contemporary,Epidemic,Low,0.1200,21st Century
37,COVID-19,SARS-CoV-2,Virus,2019,2023.0,4.0,China,Global,7,7.000000e+08,...,1.000,Airborne/Droplet,Vaccine/Lockdown,13800.0,True,Contemporary,Pandemic,High,0.7000,21st Century
38,Monkeypox 2022,Monkeypox Virus,Virus,2022,2023.0,1.0,Multiple,Global,6,9.000000e+04,...,0.110,Contact,Vaccine,3.0,True,Contemporary,Epidemic,Minimal,0.0660,21st Century
39,Cholera Haiti,Vibrio cholerae,Bacteria,2010,2019.0,9.0,Haiti,Regional,1,8.200000e+05,...,1.160,Waterborne,ORS,2.0,False,Contemporary,Epidemic,Low,0.1160,21st Century
40,Yellow Fever Angola,Yellow Fever Virus,Virus,2015,2016.0,1.0,Angola,Regional,1,7.334000e+03,...,4.840,Vector,Vaccine,1.0,True,Contemporary,Outbreak,Minimal,0.4840,21st Century
41,Plague Madagascar,Yersinia pestis,Bacteria,2017,2017.0,1.0,Madagascar,Local,1,2.348000e+03,...,8.600,Airborne/Vector,Antibiotics,1.0,True,Contemporary,Outbreak,Minimal,0.8600,21st Century
42,Nipah Virus Kerala,Nipah Virus,Virus,2018,2023.0,5.0,India,Local,1,2.300000e+01,...,91.300,Contact/Bats,Isolation,1.0,True,Contemporary,Outbreak,Minimal,5.0000,21st Century
43,Marburg Germany,Marburg Virus,Virus,1967,1967.0,1.0,Germany,Local,1,3.100000e+01,...,NaN,Contact,Isolation,1.0,True,Modern,Outbreak,Minimal,2.2600,20th Century
44,Typhoid Fever Pakistan,Salmonella Typhi,Bacteria,2016,2023.0,7.0,Pakistan,Regional,1,1.000000e+04,...,1.000,Waterborne/Food,Antibiotics,3.0,True,Contemporary,Epidemic,Minimal,0.1000,21st Century
45,Measles DRC,Measles Virus,Virus,2019,2020.0,1.0,DRC,Regional,1,3.100000e+05,...,1.940,Airborne,Vaccine,2.0,False,Contemporary,Epidemic,Low,0.1940,21st Century
46,Pertussis USA,Bordetella pertussis,Bacteria,2012,2013.0,1.0,USA,Regional,1,4.827700e+04,...,0.040,Airborne,Vaccine,1.0,True,Contemporary,Epidemic,Minimal,0.0040,21st Century
47,Meningitis Belt Africa,Neisseria meningitidis,Bacteria,2009,2010.0,1.0,Africa,Regional,1,8.819900e+04,...,6.070,Droplet,Vaccine,3.0,True,Contemporary,Epidemic,Low,0.6070,21st Century
48,Anthrax Siberia,Bacillus anthracis,Bacteria,2016,2016.0,1.0,Russia,Local,1,2.300000e+03,...,0.040,Contact,Antibiotics,1.0,False,Contemporary,Outbreak,Minimal,0.0040,21st Century
49,Rocky Mountain Spotted Fever,Rickettsia rickettsii,Bacteria,1980,2023.0,43.0,USA,Regional,1,6.000000e+03,...,1.000,Vector,Antibiotics,2.0,True,Modern,Endemic,Minimal,0.1000,20th Century
50,Hantavirus,Hantavirus,Virus,1993,2023.0,30.0,USA,Regional,2,8.330000e+02,...,37.300,Contact,Supportive Care,2.0,True,Modern,Endemic,Minimal,7.4600,20th Century
51,Q Fever Netherlands,Coxiella burnetii,Bacteria,2007,2010.0,3.0,Netherlands,Regional,1,4.000000e+03,...,1.850,Airborne,Antibiotics,1.0,True,Contemporary,Epidemic,Minimal,0.1850,21st Century

#### Missing Values :

In [47]:
df.isnull().sum()

Event_Name                     0
Pathogen_Name                  0
Pathogen_Type                  0
Start_Year                     0
End_Year                       0
Duration_Years                 3
Origin_Region                  0
Geographic_Spread              0
Continents_Affected            0
Estimated_Cases                2
Estimated_Deaths               0
Case_Fatality_Rate_Pct         1
Primary_Transmission           0
Containment_Method             1
Economic_Impact_Billion_USD    2
Medical_Breakthrough           0
Era                            0
WHO_Classification             2
Mortality_Scale                0
Spread_Score                   0
Century                        0
dtype: int64

In [45]:
df['End_Year'].mode()[0]
df['End_Year'] = df['End_Year'].fillna(df['End_Year'].mode()[0])